moveit_controller_manager: moveit_fake_controller_manager/MoveItFakeControllerManager

moveit_fake_controller_manager:
  controller_names:
    - right_arm_controller

  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - r_shoulder_pitch_joint
      - r_shoulder_roll_joint
      - r_upper_arm_yaw_joint
      - r_elbow_pitch_joint
      - r_lower_arm_yaw_joint
