// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RobstrideModel } from "./RobstrideModel";

/**
 * Protocol family inside actuators. Extensible (new vendor → new variant).
 *
 * Internally tagged (`kind`) so serde YAML/JSON round-trips cleanly with `Device`'s own `kind`
 * field (ts-rs-compatible; avoids mixed untagged/tagged enum deserialization issues).
 */
export type ActuatorFamily = { "kind": "robstride", model: RobstrideModel, };
