// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JointKind } from "./JointKind";
import type { TravelLimits } from "./TravelLimits";

/**
 * Fields shared by all actuators regardless of vendor family.
 */
export type ActuatorCommon = { role: string, can_bus: string, can_id: number, present: boolean, verified: boolean, commissioned_at: string | null, firmware_version: string | null, travel_limits: TravelLimits | null, commissioned_zero_offset: number | null, predefined_home_rad: number | null, limb: string | null, joint_kind: JointKind | null, 
/**
 * YAML fragment (string) preserving v1 `extra` map entries so nothing is silently dropped.
 */
notes_yaml: string | null, };
