// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Standard error envelope for API responses.
 */
export type ApiError = { error: string, detail: string | null, };
