// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatteryCommon = { role: string, can_bus: string, can_id: number, present: boolean, notes: string | null, };
