// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One motor's boot-time gate state. Initialized to `Unknown` for every
 * present motor at daemon start; transitions through the states described
 * in the boot-flow diagram. Only `Homed` permits `enable`.
 *
 * Not `Copy`: `HomeFailed` carries the abort reason as a `String` so the
 * SPA can show what went wrong without a follow-up audit-log query.
 * All callers that previously relied on implicit copies use `.cloned()`
 * or pattern-bind by reference.
 */
export type BootState = { "kind": "unknown" } | { "kind": "out_of_band", mech_pos_rad: number, min_rad: number, max_rad: number, } | { "kind": "auto_recovering", from_rad: number, target_rad: number, progress_rad: number, } | { "kind": "in_band" } | { "kind": "homed" } | { "kind": "offset_changed", stored_rad: number, current_rad: number, } | { "kind": "auto_homing", from_rad: number, target_rad: number, progress_rad: number, } | { "kind": "home_failed", reason: string, last_pos_rad: number, };
