// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compile-time binary identity (Pi release / dev host).
 */
export type BuildIdentity = { 
/**
 * Full commit SHA of this build.
 */
commit_sha: string, 
/**
 * 12-hex short SHA, aligned with `latest.json` / Pi tags.
 */
short_sha: string, 
/**
 * RFC 3339 UTC from CI, `git` committer date, or `unknown`.
 */
built_at: string, 
/**
 * `CARGO_PKG_VERSION` of the `cortex` crate.
 */
package_version: string, };
