// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Latest release from GitHub `latest.json` (if fetched). Matches `cortex-update.sh` manifest.
 */
export type ChannelLatest = { commit_sha: string | null, short_sha: string | null, built_at: string | null, 
/**
 * Last fetch/parse error (e.g. offline); UI should treat stale check as unknown.
 */
manifest_error: string | null, };
