// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WtSubscribe } from "./WtSubscribe";

/**
 * Anything the SPA can send the daemon over a WebTransport bidi stream.
 *
 * # Adding a variant
 *
 * 1. Add the variant + ts-rs export here.
 * 2. Add a dispatch arm in
 *    [`crate::wt_router::dispatch_client_frame`].
 * 3. Add a SPA helper in `link/src/lib/wt/clientStream.ts`.
 *
 * Variant names use snake_case in CBOR (matches every other client-side
 * enum on the wire). The SPA's `clientStream.ts` is the single source of
 * truth for the encoding and is auto-generated against the ts-rs export
 * of this enum.
 */
export type ClientFrame = { "kind": "subscribe" } & WtSubscribe | { "kind": "motion_jog", role: string, vel_rad_s: number, } | { "kind": "motion_heartbeat", role: string, } | { "kind": "motion_stop", role: string, };
