// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CurrentSafetyTiers = { mild_ratio: number, moderate_ratio: number, severe_ratio: number, 
/**
 * Severe threshold while idle/backdriven. `None` means idle never trips.
 */
severe_idle_ratio: number | null, i2t_ratio: number, 
/**
 * Optional absolute severe clamp in RMS amps. The lower of ratio-derived
 * and absolute clamp wins.
 */
severe_abs_arms: number | null, };
