// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildIdentity } from "./BuildIdentity";
import type { ChannelLatest } from "./ChannelLatest";
import type { UpdaterStatus } from "./UpdaterStatus";

/**
 * Build stamp + `latest.json` + updater: surfaced on `ServerConfig` for the Connection card.
 */
export type DeploymentInfo = { build: BuildIdentity, latest: ChannelLatest, 
/**
 * `true` when we know `build.commit_sha != latest.commit_sha` (and both are present).
 */
is_stale: boolean, 
/**
 * `true` when `latest.json` was fetched and parsed; `is_stale` is meaningful when this is set.
 */
latest_manifest_ok: boolean, updater: UpdaterStatus, };
