// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Actuator } from "./Actuator";
import type { Battery } from "./Battery";
import type { Sensor } from "./Sensor";

/**
 * Inventory row: actuator, sensor, or battery. JSON/YAML uses `kind` as the tag.
 */
export type Device = { "kind": "actuator" } & Actuator | { "kind": "sensor" } & Sensor | { "kind": "battery" } & Battery;
