// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImuSample = { 
/**
 * Unit quaternion from the BNO085 rotation-vector report: [x, y, z, w].
 */
quaternion_xyzw: [number, number, number, number], accel_m_s2: [number, number, number], gyro_rad_s: [number, number, number], 
/**
 * Rotation-vector accuracy status: 0 unreliable, 1 low, 2 medium, 3 high.
 */
rotation_accuracy: number, rotation_accuracy_label: string, };
