// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical position of a joint in the kinematic chain. Used to derive the
 * proximal-to-distal home order without operator input.
 */
export type JointKind = "waist_rotation" | "spine_pitch" | "shoulder_pitch" | "shoulder_roll" | "upper_arm_yaw" | "elbow_pitch" | "forearm_roll" | "wrist_pitch" | "wrist_yaw" | "wrist_roll" | "gripper" | "hip_yaw" | "hip_roll" | "hip_pitch" | "knee_pitch" | "ankle_pitch" | "ankle_roll" | "neck_pitch" | "neck_yaw";
