// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-actuator dynamics and safety envelope, stored in inventory.
 *
 * Operators configure this per joint to declare the gravity and motion
 * constraints specific to that joint's position in the kinematic chain
 * and attached payload.
 */
export type JointDynamics = { 
/**
 * Continuous torque the actuator can sustain indefinitely without
 * thermal damage (Nm). Must be <= peak torque. For RS03: 20 Nm rated.
 */
continuous_torque_nm: number | null, 
/**
 * Structural torque limit of the joint/bracket/mounting (Nm).
 * The weakest mechanical element in the load path. If exceeded,
 * hardware breaks regardless of actuator capability.
 */
structural_torque_nm: number | null, 
/**
 * Estimated gravity hold torque at worst-case pose (Nm).
 * Computed offline from mass/COM/lever-arm or measured empirically.
 * When set, preflight refuses motion if this exceeds the effective
 * torque ceiling minus the configured margin.
 */
gravity_torque_nm: number | null, 
/**
 * Safety margin ratio applied on top of gravity_torque_nm. The
 * effective requirement is `gravity_torque_nm * (1 + margin)`.
 * Default 0.25 (25% headroom for dynamic loads, friction, estimation error).
 */
gravity_margin: number, 
/**
 * Maximum velocity allowed for this joint (rad/s). Overrides the
 * global pattern/jog caps when set to a lower value.
 */
max_velocity_rad_s: number | null, 
/**
 * Maximum acceleration allowed for this joint (rad/s^2).
 */
max_acceleration_rad_s2: number | null, 
/**
 * Maximum jerk (rad/s^3). Limits the rate of acceleration change
 * to protect gearboxes and reduce shock loads.
 */
max_jerk_rad_s3: number | null, 
/**
 * Motor torque constant (Nm/A). When known, enables current-to-torque
 * conversion for tighter envelope checks. RS03 reports Kt via telemetry
 * but the value varies per unit (spec: 2.36, observed: 1.53).
 */
kt_nm_per_amp: number | null, 
/**
 * Whether this joint is considered "loaded" (carries significant
 * distal mass). Loaded joints get stricter defaults: current watchdog
 * enforces (not observe-only), gravity checks are mandatory when
 * gravity_torque_nm is set.
 */
loaded: boolean, };
