// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One motor contributing to a [`limb_quarantined`](ApiError::error) refusal.
 */
export type LimbQuarantineMotor = { role: string, 
/**
 * [`BootState`](crate::boot_state::BootState) kind string (`snake_case`).
 */
state_kind: string, };
