// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { LogLevel } from "./LogLevel";
import type { LogSource } from "./LogSource";

/**
 * One captured log entry — the unit the SPA Logs page paginates and tails.
 *
 * Layout matches the SQLite schema in [`crate::log_store`]; `id` is the
 * primary key and the keyset cursor for pagination. `audit_*` and
 * `session_id` / `remote` are populated only for `source = Audit` rows.
 */
export type LogEntry = { id: bigint, t_ms: bigint, level: LogLevel, source: LogSource, target: string, message: string, 
/**
 * Free-form key/value bag (tracing fields or audit details). Always
 * an object shape on the wire; missing-or-empty serializes as `{}`.
 */
fields: JsonValue, 
/**
 * Span path, e.g. `motion::sweep:tick`. `None` outside any span.
 */
span: string | null, action: string | null, audit_target: string | null, result: string | null, session_id: string | null, remote: string | null, };
