// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

/**
 * One parsed `EnvFilter` directive. `target = None` means the bare
 * default level (`info` in `info,rudydae=debug`).
 */
export type LogFilterDirective = { target: string | null, level: LogLevel, };
