// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogFilterDirective } from "./LogFilterDirective";
import type { LogLevel } from "./LogLevel";

/**
 * Snapshot of the runtime tracing-filter state. `raw` round-trips through
 * `EnvFilter::try_new` so the SPA's "Advanced" textarea reads back exactly
 * what the daemon parses.
 */
export type LogFilterState = { default: LogLevel, directives: Array<LogFilterDirective>, raw: string, };
