// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity level for a captured log entry. Mirrors `tracing::Level`'s
 * 5-level vocabulary; the daemon stores it as a small integer in SQLite
 * (`trace=0 .. error=4`) and exposes the string form to the SPA so JSON
 * reads stay readable.
 */
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";
