// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a log entry came from. `Tracing` is anything that flowed through
 * the tracing subscriber (rudydae internals, axum traces, etc.); `Audit`
 * is the operator-action stream that also lands in `audit.jsonl`.
 */
export type LogSource = "tracing" | "audit";
