// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed-loop motion pattern the operator asked for. Carried in the
 * `MotionRegistry` for the lifetime of one run; the per-pattern step
 * function in [`crate::motion::patterns::sweep`] /
 * [`crate::motion::patterns::wave`] reads it on every tick.
 */
export type MotionIntent = { "kind": "sweep", speed_rad_s: number, turnaround_rad: number, } | { "kind": "wave", center_rad: number, amplitude_rad: number, speed_rad_s: number, turnaround_rad: number, } | { "kind": "jog", vel_rad_s: number, };
