// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed-loop motion pattern the operator asked for. Carried in the
 * `MotionRegistry` for the lifetime of one run; the per-pattern step
 * function in [`crate::motion::sweep`] / [`crate::motion::wave`] /
 * [`crate::motion::jog`] reads it on every tick.
 *
 * The variants are intentionally minimal: if a pattern needs derived
 * state (turnaround direction, the band-edge midpoint, etc.) the
 * controller computes it once at start and stashes it inline. Keeping
 * `MotionIntent` parameter-only makes "operator updated the slider
 * mid-run" a single `swap` on a `watch::Sender` rather than a
 * destructive restart.
 */
export type MotionIntent = { "kind": "sweep", 
/**
 * Magnitude of the velocity setpoint, in rad/s. Always positive
 * here; the controller alternates the sign at each band edge.
 */
speed_rad_s: number, 
/**
 * Inset from each band edge at which the controller flips
 * direction. Defaults to `0.05` (~2.9 deg) when the REST handler
 * omits it. Larger values trade range for a softer turnaround.
 */
turnaround_rad: number, } | { "kind": "wave", center_rad: number, amplitude_rad: number, speed_rad_s: number, 
/**
 * Same role as `Sweep::turnaround_rad`; defaults to `0.02`
 * (~1.1 deg) when omitted.
 */
turnaround_rad: number, } | { "kind": "jog", vel_rad_s: number, };
