// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminator for [`MotionStatus::state`]. `Running` is high-rate;
 * `Stopped` is one-shot at exit and carries the reason inline.
 */
export type MotionState = "running" | "stopped";
