// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MotionState } from "./MotionState";

/**
 * One snapshot from a running [`crate::motion::controller`]. Broadcast
 * on `state.motion_status_tx` after every successful tick (so the SPA
 * can render the live "running: sweep" badge without polling) and a
 * final time on every exit path with `state = Stopped`.
 *
 * `t_ms` is wallclock at emission so subscribers can detect a stalled
 * controller by comparing to `Date.now()`. `vel_rad_s` is whatever the
 * controller most recently *commanded* (post-clamp), not what the motor
 * reports — pair with `MotorFeedback::mech_vel_rad_s` for the measured
 * value.
 */
export type MotionStatus = { run_id: string, role: string, 
/**
 * snake_case pattern name (`"sweep"`, `"wave"`, `"jog"`).
 */
kind: string, t_ms: bigint, state: MotionState, 
/**
 * Last commanded velocity (rad/s). Always present even when stopped
 * so the UI can render "stopped at +0.25 rad/s" without inventing a
 * sentinel.
 */
vel_rad_s: number, 
/**
 * Live position the controller saw at emission time, in rad. Saves
 * the SPA a join against `motor_feedback` for the running-badge view.
 */
mech_pos_rad: number, 
/**
 * Reason this status was emitted. Always `None` while running;
 * populated on the terminal `Stopped` frame.
 */
reason: string | null, };
