// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BootState } from "./BootState";
import type { JointKind } from "./JointKind";
import type { MotorFeedback } from "./MotorFeedback";
import type { TravelLimits } from "./TravelLimits";

/**
 * GET /api/motors — list summary.
 */
export type MotorSummary = { role: string, can_bus: string, can_id: number, firmware_version: string | null, verified: boolean, present: boolean, 
/**
 * Daemon's best-effort view of whether torque is currently enabled.
 */
enabled: boolean, travel_limits: TravelLimits | null, 
/**
 * Target angle (radians) for boot-time auto-home. `None` uses 0.0 rad;
 * when set, must stay within `travel_limits`.
 */
predefined_home_rad: number | null, latest: MotorFeedback | null, 
/**
 * Per-power-cycle gate state. UI renders a colored badge driven off
 * the variant; OutOfBand carries enough detail to display
 * "X.X deg outside [Y.Y, Z.Z]" without a second roundtrip.
 */
boot_state: BootState, 
/**
 * Limb assignment, if any (`left_arm`, `right_leg`, etc.). None for
 * ungrouped motors that haven't been assigned via the inventory tab.
 */
limb: string | null, 
/**
 * Canonical position in the kinematic chain. None for ungrouped motors.
 */
joint_kind: JointKind | null, };
