// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TravelLimits } from "./TravelLimits";

export type Motor = { role: string, can_bus: string, can_id: number, firmware_version: string | null, verified: boolean, commissioned_at: string | null, 
/**
 * Whether the physical motor is wired into the bus right now.
 *
 * Defaults to `true` so existing inventory entries keep behaving as before.
 * Set to `false` for placeholder entries (motor planned but not yet on the
 * bus) or for temporarily-removed motors. Affects:
 *
 *   * Real-CAN telemetry: rudydae skips polling absent motors so an
 *     unanswered iface doesn't fill the SocketCAN txqueue and start
 *     returning ENOBUFS (errno 105) on every send.
 *   * Control plane: enable / stop / save / set_zero on an absent motor
 *     are rejected at the API layer with a clean `409 Conflict` rather
 *     than queuing CAN frames that will never get an ACK.
 *   * Mock CAN + the REST `/api/motors` listing still include absent
 *     motors so the UI can show them with an "absent" badge.
 */
present: boolean, 
/**
 * Per-motor soft travel-limits band, in radians. None ≡ "use the spec
 * default" (which is currently the full RS03 ±2-turn envelope from
 * `protocol.position_min_rad / position_max_rad`).
 *
 * Edited via `PUT /api/motors/:role/travel_limits`; persisted by
 * rewriting `inventory.yaml` atomically (see `inventory::write_atomic`).
 * Enforced by `crate::can::travel::enforce_travel_band` on every
 * commanded move (jog now, future move-to).
 */
travel_limits: TravelLimits | null, };
