// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JointKind } from "./JointKind";
import type { TravelLimits } from "./TravelLimits";

export type Motor = { role: string, can_bus: string, can_id: number, firmware_version: string | null, verified: boolean, commissioned_at: string | null, 
/**
 * Whether the physical motor is wired into the bus right now.
 *
 * Defaults to `true` so existing inventory entries keep behaving as before.
 * Set to `false` for placeholder entries (motor planned but not yet on the
 * bus) or for temporarily-removed motors. Affects:
 *
 *   * Real-CAN telemetry: cortex skips polling absent motors so an
 *     unanswered iface doesn't fill the SocketCAN txqueue and start
 *     returning ENOBUFS (errno 105) on every send.
 *   * Control plane: enable / stop / save / set_zero on an absent motor
 *     are rejected at the API layer with a clean `409 Conflict` rather
 *     than queuing CAN frames that will never get an ACK.
 *   * Mock CAN + the REST `/api/motors` listing still include absent
 *     motors so the UI can show them with an "absent" badge.
 */
present: boolean, 
/**
 * Per-motor soft travel-limits band, in radians. None ≡ "use the spec
 * default" (which is currently the full RS03 ±2-turn envelope from
 * `protocol.position_min_rad / position_max_rad`).
 *
 * Edited via `PUT /api/motors/:role/travel_limits`; persisted by
 * rewriting `inventory.yaml` atomically (see `inventory::write_atomic`).
 * Enforced by `crate::can::travel::enforce_travel_band` on every
 * commanded move (jog now, future move-to).
 */
travel_limits: TravelLimits | null, 
/**
 * Firmware `add_offset` (parameter 0x702B) recorded at commissioning
 * time, in radians. `None` means "this motor has never been
 * commissioned via `POST /api/motors/:role/commission`" — the boot
 * orchestrator skips uncommissioned motors with a clear log message
 * and they continue to require the manual `Verify & Home` flow on
 * every boot, exactly as before.
 *
 * Once set, every boot the daemon reads `add_offset` over CAN and
 * compares against this value within
 * `cfg.safety.commission_readback_tolerance_rad`. Mismatch surfaces
 * as `BootState::OffsetChanged { stored, current }` (Class-1
 * shenanigan detection) and refuses motion until the operator either
 * re-commissions or restores via
 * `POST /api/motors/:role/restore_offset`.
 *
 * Written ONLY by `POST /api/motors/:role/commission`; never edited
 * by hand. The endpoint sequences type-6 SetZero + type-22 SaveParams
 * + a readback of `add_offset` and stores the readback value here so
 * the on-disk record is exactly what the firmware confirmed it
 * flashed. See [the commissioned-zero plan][1].
 *
 * [1]: ../../../.cursor/plans/quick-home_commissioned_zero_boot.plan.md
 */
commissioned_zero_offset: number | null, 
/**
 * Per-motor target angle for the boot orchestrator's auto-home flow,
 * in radians. `None` is interpreted as `0.0` by the orchestrator —
 * "drive this joint to its commissioned neutral on every boot."
 *
 * Set this when a particular joint's neutral pose isn't the same as
 * its commissioned zero (e.g. an arm whose comfortable resting pose
 * differs from the position where the operator commissioned it).
 * Must be inside `travel_limits`; the eventual
 * `PUT /api/motors/:role/predefined_home` endpoint enforces that
 * invariant at write time.
 *
 * Read by `boot_orchestrator::maybe_run` (lands in Phase C of the
 * commissioned-zero plan) and by the eventual real `home_all`
 * implementation. Independent of `travel_limits`: the band is the
 * safe envelope, this is the goal pose inside it.
 */
predefined_home_rad: number | null, 
/**
 * Free-form limb identifier (`left_arm`, `right_leg`, `torso`, `head`).
 * Optional today: motors without `limb` are skipped by `POST /home_all`.
 * Once set, the role becomes a derived identifier of the form
 * `{limb}.{joint_kind}`; see [`Self::canonical_role`].
 */
limb: string | null, 
/**
 * Canonical position in the kinematic chain. When set, `limb` must
 * also be set and `role` must equal `{limb}.{joint_kind.as_snake_case}`.
 */
joint_kind: JointKind | null, };
