// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MotorFeedback } from "./MotorFeedback";
import type { TravelLimits } from "./TravelLimits";

/**
 * GET /api/motors — list summary.
 */
export type MotorSummary = { role: string, can_bus: string, can_id: number, firmware_version: string | null, verified: boolean, present: boolean, travel_limits: TravelLimits | null, latest: MotorFeedback | null, };
