// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * POST /api/motors/:role/params/sync body.
 */
export type ParamSyncRequest = { 
/**
 * When `None`, sync every param that currently has drift.
 */
names?: Array<string>, };
