// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * PUT /api/motors/:role/params/:index body.
 */
export type ParamWrite = { value: JsonValue, 
/**
 * Ignored: writes always persist to actuator flash (type-22) and `inventory.desired_params`.
 */
save_after: boolean, };
