// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParamDescriptor = { 
/**
 * Hex index like `0x700B`, stored as u16 after parsing.
 */
index: number, type: string, units: string | null, 
/**
 * Present on firmware_limits entries only.
 */
hardware_range: [number, number] | null, description: string | null, values: { [key in string]: number } | null, };
