// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamDrift } from "./ParamDrift";
import type { JsonValue } from "./serde_json/JsonValue";

export type ParamValue = { name: string, index: number, type: string, units: string | null, value: JsonValue, hardware_range: [number, number] | null, 
/**
 * From `inventory.desired_params` for writable params.
 */
desired?: JsonValue, 
/**
 * Present when live value differs from desired (writable limits only).
 */
drift?: ParamDrift, };
