// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamValue } from "./ParamValue";

/**
 * GET /api/motors/:role/params — full catalog snapshot.
 */
export type ParamSnapshot = { role: string, values: { [key in string]: ParamValue }, };
