// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayModel } from "./DisplayModel";
import type { FanModel } from "./FanModel";
import type { LedModel } from "./LedModel";
import type { MicrophoneModel } from "./MicrophoneModel";
import type { SpeakerModel } from "./SpeakerModel";

export type PeripheralFamily = { "kind": "microphone", model: MicrophoneModel, } | { "kind": "speaker", model: SpeakerModel, } | { "kind": "led", model: LedModel, } | { "kind": "display", model: DisplayModel, } | { "kind": "fan", model: FanModel, };
