// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PeripheralCommon = { role: string, can_bus: string, can_id: number, present: boolean, verified: boolean, commissioned_at: string | null, notes: string | null, 
/**
 * Which limb the peripheral is mounted on (`head`, `torso`, `right_arm`, …).
 * Optional — peripherals like fans or status LEDs may not belong to any
 * specific limb.
 */
limb: string | null, };
