// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type PutSettingRequest = { 
/**
 * JSON `Value` appropriate for the key (bool, number, or null for optional float).
 */
value: JsonValue, };
