// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsApplyMode } from "./SettingsApplyMode";
import type { JsonValue } from "./serde_json/JsonValue";

export type PutSettingResponse = { ok: boolean, key: string, effective: JsonValue, apply_mode: SettingsApplyMode, note: string | null, };
