// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * POST /api/reminders body and PUT /api/reminders/:id body.
 */
export type ReminderInput = { text: string, due_at: string | null, done: boolean, };
