// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One operator reminder. File-backed in `.cortex/reminders.json`.
 * Created/edited/deleted via `/api/reminders[/:id]`.
 */
export type Reminder = { id: string, text: string, 
/**
 * Optional ISO 8601 due date; the UI renders relative ("in 2h", "overdue").
 */
due_at: string | null, done: boolean, 
/**
 * Wallclock at creation, ms since unix epoch.
 */
created_ms: bigint, };
