// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Concrete RobStride SKU; drives `config/actuators/robstride_rs0X.yaml` lookup.
 */
export type RobstrideModel = "rs01" | "rs02" | "rs03" | "rs04";
