// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A condition explaining why the runtime is not simply `ready`.
 */
export type RuntimeBlocker = { kind: string, role: string | null, message: string, };
