// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeBlocker } from "./RuntimeBlocker";
import type { RuntimeMotion } from "./RuntimeMotion";
import type { RuntimeState } from "./RuntimeState";

/**
 * Current read-only runtime FSM snapshot.
 */
export type RuntimeStatus = { t_ms: bigint, state: RuntimeState, 
/**
 * Stable snake_case reason for the chosen state.
 */
reason: string, can_mock: boolean, can_ready: boolean, 
/**
 * Informational only in this first ADR-0008 implementation. Later gate
 * PRs will make this field line up with enforcement.
 */
can_accept_motion: boolean, active_motions: Array<RuntimeMotion>, enabled_roles: Array<string>, position_hold_roles: Array<string>, blockers: Array<RuntimeBlocker>, };
