// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * High-level daemon runtime state from ADR-0008.
 */
export type RuntimeState = "passive" | "commissioning" | "ready" | "homing" | "holding" | "manual_jog" | "primitive_running" | "faulted" | "e_stop";
