// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One active motion summarized for runtime-status consumers.
 */
export type RuntimeMotion = { run_id: string, role: string, kind: string, started_at_ms: bigint, };
