// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reliable broadcast for safety-relevant transitions.
 */
export type SafetyEvent = { "kind": "estop", t_ms: bigint, source: string, } | { "kind": "lock_changed", t_ms: bigint, holder: string | null, } | { "kind": "travel_limit_violation", t_ms: bigint, role: string, attempted_rad: number, min_rad: number, max_rad: number, } | { "kind": "auto_recovery_attempted", t_ms: bigint, role: string, from_rad: number, target_rad: number, delta_rad: number, } | { "kind": "auto_recovery_succeeded", t_ms: bigint, role: string, final_pos_rad: number, ticks: number, } | { "kind": "auto_recovery_failed", t_ms: bigint, role: string, reason: string, last_pos_rad: number, } | { "kind": "auto_recovery_refused", t_ms: bigint, role: string, reason: string, delta_rad: number, } | { "kind": "homed", t_ms: bigint, role: string, final_pos_rad: number, samples_count: number, } | { "kind": "motor_renamed", t_ms: bigint, old_role: string, new_role: string, } | { "kind": "commissioned", t_ms: bigint, role: string, offset_rad: number, };
