// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reliable broadcast for safety-relevant transitions.
 */
export type SafetyEvent = { "kind": "estop", t_ms: bigint, source: string, } | { "kind": "lock_changed", t_ms: bigint, holder: string | null, } | { "kind": "travel_limit_violation", t_ms: bigint, role: string, attempted_rad: number, min_rad: number, max_rad: number, };
