// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraModel } from "./CameraModel";
import type { ForceSensorModel } from "./ForceSensorModel";
import type { GyroSensorModel } from "./GyroSensorModel";
import type { LidarModel } from "./LidarModel";
import type { MotionSensorModel } from "./MotionSensorModel";

export type SensorFamily = { "kind": "motion", model: MotionSensorModel, } | { "kind": "force", model: ForceSensorModel, } | { "kind": "gyro", model: GyroSensorModel, } | { "kind": "camera", model: CameraModel, } | { "kind": "lidar", model: LidarModel, };
