// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SensorCommon = { role: string, can_bus: string, can_id: number, present: boolean, verified: boolean, commissioned_at: string | null, notes: string | null, 
/**
 * Which limb the sensor is mounted on (`head`, `torso`, `right_arm`, etc.).
 * Optional so sensors that haven't been placed yet, or sensors that don't
 * belong to a specific limb (e.g. a chest-mounted IMU could just be
 * `torso`), still parse cleanly.
 */
limb: string | null, };
