// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImuSample } from "./ImuSample";
import type { SensorHealth } from "./SensorHealth";

export type SensorSample = { 
/**
 * Wallclock at sample time, ms since unix epoch.
 */
t_ms: bigint, sensor_id: string, frame_id: string, kind: string, health: SensorHealth, stale_after_ms: bigint, message: string | null, imu: ImuSample | null, };
