// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerFeatures } from "./ServerFeatures";
import type { WebTransportAdvert } from "./WebTransportAdvert";

/**
 * GET /api/config — what the UI needs to bootstrap.
 */
export type ServerConfig = { version: string, 
/**
 * RobStride models with a loaded `robstride_*.yaml` (e.g. `RS03`), sorted for stable JSON.
 */
actuator_models: Array<string>, webtransport: WebTransportAdvert, features: ServerFeatures, };
