// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentInfo } from "./DeploymentInfo";
import type { ServerFeatures } from "./ServerFeatures";
import type { ServerPaths } from "./ServerPaths";
import type { WebTransportAdvert } from "./WebTransportAdvert";

/**
 * GET /api/config — what the UI needs to bootstrap.
 */
export type ServerConfig = { 
/**
 * Workspace package version; same as `deployment.build.package_version`.
 */
version: string, 
/**
 * RobStride models with a loaded `robstride_*.yaml` (e.g. `RS03`), sorted for stable JSON.
 */
actuator_models: Array<string>, webtransport: WebTransportAdvert, features: ServerFeatures, paths: ServerPaths, deployment: DeploymentInfo, };
