// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filesystem paths the daemon uses for read/write (operator transparency).
 */
export type ServerPaths = { 
/**
 * Path cortex reads and writes for live inventory (same file as
 * `PUT`/`DELETE` that mutate the catalog). On the Pi this is usually
 * `/var/lib/rudy/inventory.yaml`, not the read-only seed under
 * `/opt/rudy/config/actuators/`.
 */
inventory: string, };
