// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingEntry } from "./SettingEntry";

/**
 * Top-level `GET /api/settings`.
 */
export type SettingsGetResponse = { 
/**
 * When the SQLite runtime store is off, `PUT` is rejected.
 */
runtime_db_enabled: boolean, 
/**
 * Set after corrupt-DB re-seed until `POST /api/settings/recovery/ack`.
 */
recovery_pending: boolean, entries: Array<SettingEntry>, };
