// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Apply semantics (subset of the migration plan; extend as HIL rules firm up).
 */
export type SettingsApplyMode = "read_only" | "runtime_immediate" | "requires_restart";
