// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsProfileInfo } from "./SettingsProfileInfo";

export type SettingsProfilesListResponse = { profiles: Array<SettingsProfileInfo>, };
