// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type SettingsProfileCreateRequest = { name: string, 
/**
 * Subset of `safety.*` / `telemetry.*` values to snapshot as a profile.
 */
values: { [key in string]: JsonValue }, };
