// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsProfileInfo = { name: string, key_count: number, 
/**
 * Non-cryptographic fingerprint of stored JSON (for table display).
 */
fingerprint: string, };
