// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsApplyMode } from "./SettingsApplyMode";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One registered tunable (or read-only) key.
 */
export type SettingEntry = { key: string, label: string, description: string, category: string, 
/**
 * Display hint: `bool`, `f32`, `u32`, `u64`, `option_f32`
 */
value_kind: string, unit: string | null, min: number | null, max: number | null, 
/**
 * Value from TOML seed (same as first-boot import / reset target).
 */
seed: JsonValue, 
/**
 * Live merged value (memory).
 */
effective: JsonValue, 
/**
 * Row present in `settings_kv` when the runtime DB is on.
 */
in_db: boolean, 
/**
 * Differs from seed when `in_db` (operator or import changed this key).
 */
dirty: boolean, 
/**
 * Wire apply semantics for the SPA.
 */
apply_mode: SettingsApplyMode, 
/**
 * `PUT` allowed (requires control lock; may also need motors stopped).
 */
editable: boolean, 
/**
 * Shown when `editable` is false.
 */
read_only_reason: string | null, 
/**
 * Gating hint for the operator (motion stopped on the bus).
 */
requires_motors_stopped: boolean, };
