// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-actuator stop behavior selection. Stored in inventory YAML.
 */
export type StopBehavior = "hard_stop" | "hold";
