// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pi-specific power/thermal throttling state. `now` and `ever` are derived
 * from `vcgencmd get_throttled` bits (0/2 -> now, 16/18 -> ever).
 */
export type SystemThrottled = { now: boolean, ever: boolean, raw_hex: string | null, };
