// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemTemps } from "./SystemTemps";
import type { SystemThrottled } from "./SystemThrottled";

/**
 * GET /api/system - host metrics for the operator-console dashboard.
 *
 * Linux real values come from `/proc` + `/sys` + (on the Pi) `vcgencmd`;
 * when `cfg.can.mock == true` or running on non-Linux, fields are
 * slowly-varying mock numbers and `is_mock = true`. See `system.rs`.
 */
export type SystemSnapshot = { 
/**
 * Wallclock at sample time, ms since unix epoch.
 */
t_ms: bigint, cpu_pct: number, 
/**
 * 1, 5, 15-minute load average from `/proc/loadavg`.
 */
load: [number, number, number], mem_used_mb: bigint, mem_total_mb: bigint, temps_c: SystemTemps, throttled: SystemThrottled, 
/**
 * Host/Pi uptime from `/proc/uptime`.
 */
uptime_s: bigint, 
/**
 * Cortex daemon uptime since this process started.
 */
cortex_uptime_s: bigint, hostname: string, kernel: string, 
/**
 * True when values are synthetic (no Linux host or `cfg.can.mock = true`).
 */
is_mock: boolean, };
