// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bench-routine name accepted by `POST /api/motors/:role/tests/:name`.
 */
export type TestName = "read" | "set_zero" | "smoke" | "jog" | "jog_overlimit";
