// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestLevel } from "./TestLevel";

/**
 * One progress line for a running bench routine. Streamed reliably on the
 * `test_progress` WebTransport stream.
 */
export type TestProgress = { run_id: string, role: string, 
/**
 * Per-run monotonic line counter; the SPA uses it for the React key so
 * every line lands exactly once even if the WT stream re-anchors.
 */
seq: bigint, t_ms: bigint, 
/**
 * Coarse step name (e.g. `"sanity"`, `"ramp_up"`, `"defang"`). Helps
 * the operator scan a long log.
 */
step: string, level: TestLevel, message: string, };
