// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity for one [`TestProgress`] line.
 */
export type TestLevel = "info" | "warn" | "pass" | "fail";
