// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-actuator soft travel-limits band (radians).
 */
export type TravelLimits = { min_rad: number, max_rad: number, updated_at: string | null, };
