// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pi `cortex-update` timer/service + `current.sha` mtime. Best-effort on non-Linux.
 */
export type UpdaterStatus = { 
/**
 * `true` when this host ran `systemctl` for the updater units.
 */
systemd_probed: boolean, 
/**
 * `LastTriggerUSec` from `cortex-update.timer` (human-readable) when available.
 */
last_check: string | null, 
/**
 * mtime of `/opt/rudy/current.sha` (or `RUDY_CURRENT_SHA_FILE`) in RFC 3339.
 */
last_applied: string | null, 
/**
 * `is-active` for `cortex-update.timer` — `None` if not probed.
 */
timer_active: boolean | null, 
/**
 * `is-failed` for `cortex-update.service` — `None` if not probed.
 */
service_failed: boolean | null, 
/**
 * `true` when: not probed (dev) or (timer active and service not failed on Linux).
 */
healthy: boolean, };
