// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebTransportAdvert = { enabled: boolean, 
/**
 * Fully-qualified URL the browser should open. Example:
 * `https://rudy.your-tailnet.ts.net:4433/wt`.
 */
url: string | null, };
