// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogEntry } from "./LogEntry";
import type { MotionStatus } from "./MotionStatus";
import type { MotorFeedback } from "./MotorFeedback";
import type { SafetyEvent } from "./SafetyEvent";
import type { SystemSnapshot } from "./SystemSnapshot";
import type { TestProgress } from "./TestProgress";

/**
 * Tagged-union view of every possible payload, used for tests and for the
 * generated TypeScript discriminated union. The on-wire encoding is
 * `WtEnvelope<T>` for some specific `T`; this enum is what the *frontend*
 * sees after decoding (`{kind, data}` with `data` typed by `kind`).
 *
 * The variants are kept in lockstep with `declare_wt_streams!` by hand for
 * now — small enough to be a non-issue, and ts-rs needs the explicit listing
 * to generate the discriminated union for `link/src/lib/types/WtFrame.ts`.
 * If we ever have >5 streams we can revisit with a doc-generation step.
 */
export type WtFrame = { "kind": "motor_feedback", "data": MotorFeedback } | { "kind": "system_snapshot", "data": SystemSnapshot } | { "kind": "test_progress", "data": TestProgress } | { "kind": "safety_event", "data": SafetyEvent } | { "kind": "motion_status", "data": MotionStatus } | { "kind": "log_event", "data": LogEntry };
