// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed discriminator. Used by `WtSubscribe` to filter and by the
 * router's per-stream sequence counter. The on-wire kind is the
 * snake_case literal from the macro; serde renames keep it stable.
 */
export type WtKind = "motor_feedback" | "system_snapshot" | "test_progress" | "safety_event" | "motion_status" | "log_event";
