// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WtKind } from "./WtKind";
import type { WtSubscribeFilters } from "./WtSubscribeFilters";

/**
 * WebTransport subscription request (sent on a bidirectional stream by the
 * client right after session open).
 *
 * Backwards compatibility: a session that *never* sends `WtSubscribe` gets
 * every stream the server knows about. This keeps the contract simple for
 * dumb clients (curl/wt-cli, future Python tooling) and lets the SPA evolve
 * its filter without coordinating with the daemon.
 */
export type WtSubscribe = { 
/**
 * Stream kinds the client wants. Empty list ≡ "all" (matches the
 * default-when-no-subscribe behavior).
 */
kinds: Array<WtKind>, 
/**
 * Optional per-kind narrow filters (e.g. motor roles). Today only
 * `motor_feedback` honors the value; unknown keys are ignored.
 */
filters: WtSubscribeFilters, };
