// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * WebTransport subscription request (sent on a bidirectional stream by the
 * client right after session open).
 */
export type WtSubscribe = { "kind": "feedback", roles: Array<string>, } | { "kind": "faults" } | { "kind": "logs", unit: string | null, };
