// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-kind narrow filters. Each field is optional; `None`/empty means
 * "no narrowing" (i.e. all values for that kind).
 */
export type WtSubscribeFilters = { 
/**
 * Motor roles the client cares about for `motor_feedback` frames.
 * Empty / missing ≡ all roles.
 */
motor_roles: Array<string>, };
