#!/usr/bin/env bash
# Build + install rudydae on the Pi from a local repo checkout.
# Run on the Pi as a normal user with sudo:
#   sudo bash deploy/pi5/install.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BUILD_USER="${SUDO_USER:-${USER}}"
BUILD_HOME="$(getent passwd "${BUILD_USER}" | cut -d: -f6)"
RUST_ENV="${BUILD_HOME}/.cargo/env"

echo "== Rudy Pi install =="
echo "repo: ${REPO_ROOT}"
echo "build user: ${BUILD_USER}"

if [[ -f /etc/apt/sources.list.d/ros2.list ]]; then
  echo "Removing stale ROS apt source from unsupported Ubuntu release"
  sudo rm -f /etc/apt/sources.list.d/ros2.list
  sudo rm -f /usr/share/keyrings/ros-archive-keyring.gpg
fi

sudo apt-get update
sudo apt-get install -y \
  build-essential \
  pkg-config \
  libssl-dev \
  libcap2-bin \
  curl \
  ca-certificates \
  git \
  jq \
  openssl \
  nodejs \
  npm \
  rsync

if ! sudo -u "${BUILD_USER}" bash -lc 'command -v cargo >/dev/null'; then
  echo "Installing Rust toolchain for ${BUILD_USER}"
  curl https://sh.rustup.rs -sSf | sudo -u "${BUILD_USER}" sh -s -- -y --profile minimal
fi

echo "Building SPA"
sudo -u "${BUILD_USER}" bash -lc "cd '${REPO_ROOT}/link' && npm ci && npm run build"

echo "Building rudydae"
sudo -u "${BUILD_USER}" bash -lc "source '${RUST_ENV}' 2>/dev/null || true; cd '${REPO_ROOT}/crates' && cargo build --release -p rudydae"

if ! id -u rudy >/dev/null 2>&1; then
  sudo useradd --system --home /var/lib/rudy --create-home --shell /usr/sbin/nologin rudy
fi
sudo usermod -a -G netdev rudy || true

sudo install -d -m 0755 /opt/rudy/bin /opt/rudy/config /etc/rudy /etc/rudy/docs/runbooks
sudo install -d -o rudy -g rudy -m 0755 /var/lib/rudy
sudo install -d -o rudy -g rudy -m 0750 /var/lib/rudyd/tailscale

sudo install -m 0755 "${REPO_ROOT}/crates/target/release/rudydae" /opt/rudy/bin/rudydae
sudo setcap cap_net_raw,cap_net_admin=eip /opt/rudy/bin/rudydae

rsync -a --delete "${REPO_ROOT}/config/" /opt/rudy/config/
sudo install -m 0644 "${REPO_ROOT}/docs/runbooks/operator-console.md" /etc/rudy/docs/runbooks/operator-console.md
sudo install -m 0644 "${REPO_ROOT}/deploy/pi5/rudyd.service" /etc/systemd/system/rudyd.service

declare -a CAN_BUSES=()
for iface in can0 can1; do
  if ip link show "${iface}" >/dev/null 2>&1; then
    CAN_BUSES+=("${iface}")
  fi
done
if [[ ${#CAN_BUSES[@]} -eq 0 ]]; then
  echo "No SocketCAN interfaces found. Bring up robot-can first." >&2
  exit 1
fi

TAILSCALE_IP="$(tailscale ip -4 2>/dev/null | awk 'NR==1 { print $1 }')"
if [[ -n "${TAILSCALE_IP}" ]]; then
  HTTP_BIND="${TAILSCALE_IP}:8443"
  WT_BIND="${TAILSCALE_IP}:4433"
else
  HTTP_BIND="0.0.0.0:8443"
  WT_BIND="0.0.0.0:4433"
fi

HOST_SHORT="$(hostname -s)"
MAGIC_SUFFIX="$(tailscale status --json 2>/dev/null | jq -r '.MagicDNSSuffix // empty')"
CERT_PREFIX=""
TLS_ENABLED="false"
WT_ENABLED="false"
if [[ -n "${MAGIC_SUFFIX}" ]]; then
  CERT_PREFIX="/var/lib/rudyd/tailscale/${HOST_SHORT}.${MAGIC_SUFFIX}"
  if [[ -f "${CERT_PREFIX}.crt" && -f "${CERT_PREFIX}.key" ]]; then
    TLS_ENABLED="true"
    WT_ENABLED="true"
  fi
fi

if [[ -f /etc/rudy/rudyd.toml ]]; then
  sudo cp /etc/rudy/rudyd.toml "/etc/rudy/rudyd.toml.bak.$(date +%Y%m%d%H%M%S)"
fi

{
  echo "# Rudy Pi runtime configuration."
  echo "# Generated by deploy/pi5/install.sh."
  echo
  echo "[http]"
  echo "bind = \"${HTTP_BIND}\""
  echo
  echo "[http.tls]"
  echo "enabled = ${TLS_ENABLED}"
  if [[ -n "${CERT_PREFIX}" ]]; then
    echo "cert_path = \"${CERT_PREFIX}.crt\""
    echo "key_path = \"${CERT_PREFIX}.key\""
  fi
  echo
  echo "[webtransport]"
  echo "bind = \"${WT_BIND}\""
  echo "enabled = ${WT_ENABLED}"
  echo
  echo "[paths]"
  echo "actuator_spec = \"/opt/rudy/config/actuators/robstride_rs03.yaml\""
  echo "inventory = \"/opt/rudy/config/actuators/inventory.yaml\""
  echo "audit_log = \"/var/lib/rudy/audit.jsonl\""
  echo
  echo "[can]"
  echo "mock = false"
  for iface in "${CAN_BUSES[@]}"; do
    echo
    echo "[[can.buses]]"
    echo "iface = \"${iface}\""
    echo "bitrate = 1000000"
  done
  echo
  echo "[telemetry]"
  echo "poll_interval_ms = 100"
  echo
  echo "[safety]"
  echo "# Benchtop bring-up stays open until the actuator is fully commissioned."
  echo "# Flip to true after the shoulder passes the verification checklist."
  echo "require_verified = false"
} | sudo tee /etc/rudy/rudyd.toml >/dev/null

sudo chown rudy:rudy /etc/rudy/rudyd.toml
sudo chmod 0640 /etc/rudy/rudyd.toml

sudo systemctl daemon-reload
sudo systemctl enable --now rudyd.service

echo
echo "Installed rudydae."
echo "Check status: sudo systemctl status rudyd.service"
echo "Tail logs:     sudo journalctl -u rudyd.service -f"
