#!/usr/bin/env bash
# Render /etc/rudy/rudyd.toml from the live system: detected SocketCAN
# interfaces, current Tailscale identity, and any provisioned cert files.
# Idempotent. Safe to re-run after CAN interfaces or certs change.
#
# Used by deploy/pi5/bootstrap.sh and deploy/pi5/apply-release.sh.
set -euo pipefail

CONFIG_PATH="${1:-/etc/rudy/rudyd.toml}"

declare -a CAN_BUSES=()
for iface in can0 can1; do
  if ip link show "${iface}" >/dev/null 2>&1; then
    CAN_BUSES+=("${iface}")
  fi
done
if [[ ${#CAN_BUSES[@]} -eq 0 ]]; then
  echo "render-rudyd-toml: no SocketCAN interfaces found; refusing to overwrite ${CONFIG_PATH}" >&2
  exit 1
fi

TAILSCALE_IP="$(tailscale ip -4 2>/dev/null | awk 'NR==1 { print $1 }' || true)"
if [[ -n "${TAILSCALE_IP}" ]]; then
  HTTP_BIND="${TAILSCALE_IP}:8443"
  WT_BIND="${TAILSCALE_IP}:4433"
else
  HTTP_BIND="0.0.0.0:8443"
  WT_BIND="0.0.0.0:4433"
fi

HOST_SHORT="$(hostname -s)"
MAGIC_SUFFIX="$(tailscale status --json 2>/dev/null | jq -r '.MagicDNSSuffix // empty' || true)"
CERT_PREFIX=""
TLS_ENABLED="false"
WT_ENABLED="false"
if [[ -n "${MAGIC_SUFFIX}" ]]; then
  CERT_PREFIX="/var/lib/rudyd/tailscale/${HOST_SHORT}.${MAGIC_SUFFIX}"
  if [[ -f "${CERT_PREFIX}.crt" && -f "${CERT_PREFIX}.key" ]]; then
    TLS_ENABLED="true"
    WT_ENABLED="true"
  fi
fi

if [[ -f "${CONFIG_PATH}" ]]; then
  sudo cp "${CONFIG_PATH}" "${CONFIG_PATH}.bak.$(date +%Y%m%d%H%M%S)"
fi

{
  echo "# Rudy Pi runtime configuration."
  echo "# Generated by deploy/pi5/render-rudyd-toml.sh."
  echo
  echo "[http]"
  echo "bind = \"${HTTP_BIND}\""
  echo
  echo "[http.tls]"
  echo "enabled = ${TLS_ENABLED}"
  if [[ -n "${CERT_PREFIX}" ]]; then
    echo "cert_path = \"${CERT_PREFIX}.crt\""
    echo "key_path = \"${CERT_PREFIX}.key\""
  fi
  echo
  echo "[webtransport]"
  echo "bind = \"${WT_BIND}\""
  echo "enabled = ${WT_ENABLED}"
  echo
  echo "[auth]"
  echo "token_file = \"/etc/rudy/rudyd.token\""
  echo "dev_allow_no_token = false"
  echo
  echo "[paths]"
  echo "actuator_spec = \"/opt/rudy/config/actuators/robstride_rs03.yaml\""
  echo "inventory = \"/opt/rudy/config/actuators/inventory.yaml\""
  echo "audit_log = \"/var/lib/rudy/audit.jsonl\""
  echo
  echo "[can]"
  echo "mock = false"
  for iface in "${CAN_BUSES[@]}"; do
    echo
    echo "[[can.buses]]"
    echo "iface = \"${iface}\""
    echo "bitrate = 1000000"
  done
  echo
  echo "[telemetry]"
  echo "poll_interval_ms = 100"
  echo
  echo "[safety]"
  echo "# Benchtop bring-up stays open until the actuator is fully commissioned."
  echo "# Flip to true after the shoulder passes the verification checklist."
  echo "require_verified = false"
} | sudo tee "${CONFIG_PATH}" >/dev/null

sudo chown rudy:rudy "${CONFIG_PATH}"
sudo chmod 0640 "${CONFIG_PATH}"

echo "render-rudyd-toml: wrote ${CONFIG_PATH}"
