#!/usr/bin/env bash
# Render /etc/rudy/cortex.toml from the live system: detected SocketCAN
# interfaces, current Tailscale identity, and any provisioned cert files.
# Idempotent. Safe to re-run on every release.
#
# Used by deploy/pi5/bootstrap.sh and deploy/pi5/apply-release.sh.
#
# Architecture (ADR-0004 addendum, "Tailscale Serve"):
# - HTTP listener: ALWAYS plaintext on 127.0.0.1:8443. `tailscale serve`
#   terminates TLS on the tailnet IP at :443 with the auto-managed Let's
#   Encrypt cert and proxies decrypted requests in. Nothing on the LAN can
#   reach :8443 directly.
# - WebTransport listener: HTTP/3 / QUIC on the tailnet IP at :4433, with its
#   own TLS using the same Tailscale-issued cert (`tailscale serve` cannot
#   proxy HTTP/3, so WT keeps doing TLS itself).
set -euo pipefail

CONFIG_PATH="${1:-/etc/rudy/cortex.toml}"

declare -a CAN_BUSES=()
for iface in can0 can1; do
  if ip link show "${iface}" >/dev/null 2>&1; then
    CAN_BUSES+=("${iface}")
  fi
done
if [[ ${#CAN_BUSES[@]} -eq 0 ]]; then
  echo "render-cortex-toml: no SocketCAN interfaces found; refusing to overwrite ${CONFIG_PATH}" >&2
  exit 1
fi

TAILSCALE_IP="$(tailscale ip -4 2>/dev/null | awk 'NR==1 { print $1 }' || true)"

# WebTransport binds the tailnet IP (so it's reachable from tailnet peers
# without going through the Serve proxy, which can't speak HTTP/3). Falls
# back to 0.0.0.0 only if Tailscale isn't up yet — in that case WT will end
# up disabled below anyway because there's no cert.
if [[ -n "${TAILSCALE_IP}" ]]; then
  WT_BIND="${TAILSCALE_IP}:4433"
else
  WT_BIND="0.0.0.0:4433"
fi

HOST_SHORT="$(hostname -s)"
MAGIC_SUFFIX="$(tailscale status --json 2>/dev/null | jq -r '.MagicDNSSuffix // empty' || true)"
CERT_PREFIX=""
WT_ENABLED="false"
if [[ -n "${MAGIC_SUFFIX}" ]]; then
  CERT_PREFIX="/var/lib/rudy/cortex/tailscale/${HOST_SHORT}.${MAGIC_SUFFIX}"
  if [[ -f "${CERT_PREFIX}.crt" && -f "${CERT_PREFIX}.key" ]]; then
    WT_ENABLED="true"
  fi
fi

if [[ -f "${CONFIG_PATH}" ]]; then
  sudo cp "${CONFIG_PATH}" "${CONFIG_PATH}.bak.$(date +%Y%m%d%H%M%S)"
fi

{
  echo "# Rudy Pi runtime configuration."
  echo "# Generated by deploy/pi5/render-cortex-toml.sh."
  echo "# Edit this file ONLY for one-off debugging — re-running"
  echo "# render-cortex-toml.sh (which apply-release.sh does on every update)"
  echo "# will overwrite it. The previous version is saved alongside as"
  echo "# cortex.toml.bak.<timestamp>."
  echo
  echo "[http]"
  echo "# Plaintext loopback. \`tailscale serve\` (set up by bootstrap.sh)"
  echo "# fronts this with TLS at https://\$(hostname)/."
  echo "bind = \"127.0.0.1:8443\""
  echo
  echo "[webtransport]"
  echo "bind = \"${WT_BIND}\""
  echo "enabled = ${WT_ENABLED}"
  if [[ -n "${CERT_PREFIX}" ]]; then
    echo "cert_path = \"${CERT_PREFIX}.crt\""
    echo "key_path = \"${CERT_PREFIX}.key\""
  fi
  echo
  echo "[paths]"
  echo "# actuator_spec is read-only at runtime, so it stays in the release tree."
  echo "actuator_spec = \"/opt/rudy/config/actuators/robstride_rs03.yaml\""
  echo "# inventory is read AND written by cortex (travel-limit / verified /"
  echo "# rename PUTs), so it MUST live on a writable path. /opt/rudy is the"
  echo "# read-only release tree and is also blocked by systemd's"
  echo "# ProtectSystem=strict. /var/lib/rudy is in ReadWritePaths and is"
  echo "# preserved across releases. inventory_seed below is the read-only"
  echo "# baseline shipped with the release tarball; cortex copies it over"
  echo "# the first time it boots and never touches it again."
  echo "inventory = \"/var/lib/rudy/inventory.yaml\""
  echo "inventory_seed = \"/opt/rudy/config/actuators/inventory.yaml\""
  echo "audit_log = \"/var/lib/rudy/audit.jsonl\""
  echo
  echo "[can]"
  echo "mock = false"
  for iface in "${CAN_BUSES[@]}"; do
    echo
    echo "[[can.buses]]"
    echo "iface = \"${iface}\""
    echo "bitrate = 1000000"
  done
  echo
  echo "[telemetry]"
  echo "poll_interval_ms = 100"
  echo
  echo "[safety]"
  echo "# Benchtop bring-up stays open until the actuator is fully commissioned."
  echo "# Flip to true after the shoulder passes the verification checklist."
  echo "require_verified = false"
  echo
  echo "[logs]"
  echo "# SQLite-backed log store. MUST live under a path the systemd unit"
  echo "# lists in ReadWritePaths (see deploy/pi5/cortex.service). The default"
  echo "# of .cortex/logs.db resolves against WorkingDirectory=/opt/rudy, which"
  echo "# is read-only under ProtectSystem=strict — opening the DB there fails"
  echo "# with EROFS and the daemon never reaches the HTTP listener, taking"
  echo "# the whole console offline."
  echo "db_path = \"/var/lib/rudy/logs.db\""
} | sudo tee "${CONFIG_PATH}" >/dev/null

sudo chown rudy:rudy "${CONFIG_PATH}"
sudo chmod 0640 "${CONFIG_PATH}"

echo "render-cortex-toml: wrote ${CONFIG_PATH}"
